# Generated by Django 5.1.7 on 2025-03-12 21:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id_administrador', models.AutoField(primary_key=True, serialize=False)),
                ('ubicacion', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('estado_de_la_cuenta', models.CharField(choices=[('ACTIVO', 'ACTIVO'), ('INACTIVO', 'INACTIVO')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Mantenimiento',
            fields=[
                ('id_mantenimiento', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_mantenimiento', models.CharField(choices=[('Preventivo', 'Preventivo'), ('Correctivo', 'Correctivo')], max_length=20)),
                ('descripcion', models.CharField(max_length=255)),
                ('costo', models.CharField(max_length=15)),
                ('notas_adicionales', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mecanico',
            fields=[
                ('id_mecanico', models.AutoField(primary_key=True, serialize=False)),
                ('horario_de_trabajo', models.TimeField()),
                ('experiencia_laboral', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Peritaje',
            fields=[
                ('id_peritaje', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='RepuestosModificados',
            fields=[
                ('id_repuestos_modificados', models.AutoField(primary_key=True, serialize=False)),
                ('motivo_del_cambio', models.CharField(max_length=255)),
                ('descripcion_del_cambio', models.CharField(max_length=255)),
                ('costo_repuesto', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=30)),
                ('apellidos', models.CharField(max_length=30)),
                ('telefono', models.CharField(max_length=20)),
                ('correo_electronico', models.EmailField(max_length=40)),
                ('nombre_usuario', models.CharField(max_length=30)),
                ('contraseña', models.CharField(max_length=64)),
                ('rol_usuario', models.CharField(default='Cliente', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='MecanicoMantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_mantenimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicio.mantenimiento')),
                ('id_mecanico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicio.mecanico')),
            ],
        ),
        migrations.CreateModel(
            name='Notificaciones',
            fields=[
                ('id_notificaciones', models.AutoField(primary_key=True, serialize=False)),
                ('motivo', models.CharField(max_length=45)),
                ('fecha_recordatorio', models.DateField()),
                ('hora_recordatorio', models.TimeField()),
                ('notas', models.CharField(blank=True, max_length=100, null=True)),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicio.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='MantenimientoRepuestosModificados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_mantenimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicio.mantenimiento')),
                ('id_repuestos_modificados', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicio.repuestosmodificados')),
            ],
        ),
        migrations.CreateModel(
            name='TallerMecanico',
            fields=[
                ('id_taller_mecanico', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('direccion', models.CharField(max_length=60)),
                ('telefono', models.CharField(max_length=20)),
                ('horario_de_atencion', models.TimeField()),
                ('id_administrador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicio.administrador')),
                ('id_mecanico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicio.mecanico')),
            ],
        ),
        migrations.AddField(
            model_name='mecanico',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicio.usuario'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicio.usuario'),
        ),
        migrations.AddField(
            model_name='administrador',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicio.usuario'),
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id_vehiculo', models.AutoField(primary_key=True, serialize=False)),
                ('modelo', models.CharField(max_length=4)),
                ('tipo', models.CharField(choices=[('Automovil', 'Automovil'), ('Camioneta', 'Camioneta'), ('Motocicleta', 'Motocicleta')], max_length=20)),
                ('marca', models.CharField(max_length=30)),
                ('placa', models.CharField(max_length=6)),
                ('color', models.CharField(max_length=20)),
                ('kilometraje', models.IntegerField()),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicio.cliente')),
                ('id_mantenimiento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inicio.mantenimiento')),
                ('id_peritaje', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inicio.peritaje')),
                ('id_repuestos_modificados', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inicio.repuestosmodificados')),
            ],
        ),
        migrations.CreateModel(
            name='Soat',
            fields=[
                ('id_soat', models.AutoField(primary_key=True, serialize=False)),
                ('estado_poliza', models.CharField(choices=[('Activa', 'Activa'), ('Espera', 'Espera'), ('En espera', 'En espera')], max_length=20)),
                ('aseguradora', models.CharField(max_length=30)),
                ('fecha_vencimiento', models.DateField()),
                ('id_vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicio.vehiculo')),
            ],
        ),
        migrations.CreateModel(
            name='MantenimientoProgramado',
            fields=[
                ('id_mantenimiento', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_Mantenimiento', models.CharField(max_length=30)),
                ('fecha_mantenimiento', models.DateField()),
                ('hora_mantenimiento', models.TimeField()),
                ('notas', models.CharField(blank=True, max_length=100, null=True)),
                ('id_mecanico', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inicio.mecanico')),
                ('id_taller_mecanico', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inicio.tallermecanico')),
                ('id_vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicio.vehiculo')),
            ],
        ),
        migrations.CreateModel(
            name='VehiculoMantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_mantenimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicio.mantenimiento')),
                ('id_vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicio.vehiculo')),
            ],
        ),
        migrations.CreateModel(
            name='VehiculoPeritaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_peritaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicio.peritaje')),
                ('id_vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicio.vehiculo')),
            ],
        ),
        migrations.CreateModel(
            name='VehiculoRepuestosModificados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_repuestos_modificados', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicio.repuestosmodificados')),
                ('id_vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicio.vehiculo')),
            ],
        ),
    ]
