# Generated by Django 5.1.6 on 2025-03-19 02:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0003_alter_usuario_telefono_alter_vehiculo_placa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='soat',
            name='estado_poliza',
        ),
        migrations.AddField(
            model_name='soat',
            name='fecha_emision',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='soat',
            name='numero_poliza',
            field=models.CharField(default='0000000000', max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='soat',
            name='valor_soat',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='soat',
            name='aseguradora',
            field=models.CharField(max_length=50),
        ),
    ]
