# Generated by Django 5.1.6 on 2025-03-17 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0003_peritaje_costo_peritaje_notas_adicionales_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='repuestosmodificados',
            old_name='descripcion_del_cambio',
            new_name='descripcion',
        ),
        migrations.RenameField(
            model_name='repuestosmodificados',
            old_name='motivo_del_cambio',
            new_name='motivo',
        ),
        migrations.RemoveField(
            model_name='repuestosmodificados',
            name='costo_repuesto',
        ),
        migrations.AddField(
            model_name='repuestosmodificados',
            name='costo',
            field=models.CharField(default=123456, max_length=15),
            preserve_default=False,
        ),
    ]
