# Generated by Django 5.1.7 on 2025-03-20 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0004_remove_soat_estado_poliza_soat_fecha_emision_and_more'),
        ('inicio', '0004_rename_descripcion_del_cambio_repuestosmodificados_descripcion_and_more'),
    ]

    operations = [
    ]
