# Generated by Django 5.1.6 on 2025-03-23 21:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0005_merge_20250320_0635'),
    ]

    operations = [
        migrations.CreateModel(
            name='MecanicoPeritaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_mecanico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicio.mecanico')),
                ('id_peritaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicio.peritaje')),
            ],
        ),
        migrations.CreateModel(
            name='MecanicoRepuestosModificados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_mecanico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicio.mecanico')),
                ('id_repuestos_modificados', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicio.repuestosmodificados')),
            ],
        ),
    ]
