# Generated by Django 5.1.6 on 2025-03-27 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0006_mecanicoperitaje_mecanicorepuestosmodificados'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tallermecanico',
            name='id_mecanico',
        ),
        migrations.AddField(
            model_name='mecanico',
            name='id_taller_mecanico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inicio.tallermecanico'),
        ),
    ]
