# Generated by Django 5.1.6 on 2025-03-29 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0007_remove_tallermecanico_id_mecanico_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mantenimientoprogramado',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('completado', 'Completado')], default='pendiente', max_length=20),
        ),
    ]
